// CLKCTRL.v

// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module CLKCTRL (
		input  wire  inclk,  //  altclkctrl_input.inclk
		output wire  outclk  // altclkctrl_output.outclk
	);

	CLKCTRL_altclkctrl_0 altclkctrl_0 (
		.inclk  (inclk),  //  altclkctrl_input.inclk
		.outclk (outclk)  // altclkctrl_output.outclk
	);

endmodule
