#!/bin/bash

export DIR_SIM=$PWD/../SIM_iverilog
export DIR_RTL_SYS=$PWD/../RTL
export DIR_RTL_SRC=$PWD/../RTL/MCS4

rm -f tb.vvp
iverilog -v -g2012 -o tb.vvp -c ${DIR_SIM}/flist.txt -D IVERILOG -s TB_TOP
vvp tb.vvp > log

